### ISSUE TITLE
dead "last" link

### ISSUE THREAD

**Issue by foice** [tmux-plugins/tmux-resurrect#93] opened 2015-07-29 09:02 UTC
Hello,
  I have been playing around with restoring tmux session on different machines of our little cluster. Now all session are off and I am left with one only. I give the "save" command and tmux save the session seemingly fine.

Unfortunately the restore does not work, because it complains that the restore file is missing. Indeed the .tmux/resurrect folder has these latest added files

-rw-r--r--. 1 me 1.9K Jul 21 02:13 tmux_resurrect_2015-07-21T02:13:37.txt
-rw-r--r--. 1 me 1.9K Jul 21 02:14 tmux_resurrect_2015-07-21T02:14:37.txt
lrwxr-xr-x. 1 me   38 Jul 29 10:57 last -> tmux_resurrect_2015-07-29T10:57:33.txt

and the link is pointing to file that does not exist ... any idea what is wrong here?

Cheers,
Roberto

**Comment by bruno-** [comment] 2015-07-29 11:57
That's really really unusual. Linking `last` to the "real" file happens at the end after the file already exists.

The logic for creating the resurrect file and `last` symlink is in `scripts/save.sh` file [here](https://github.com/tmux-plugins/tmux-resurrect/blob/a47236d24795356d11e4e636befa4d9500b840c2/scripts/save.sh#L256-260).

I really have no idea how to start with this so do you maybe wanna do some simple debugging? Maybe put `echo 'foobar' >> "$resurrect_file_path"` somewhere before line 260 and then verify the file gets created after save.

**Comment by foice** [comment] 2015-07-29 12:22
Thanks for your reply. Will do the test.
Might this be related to me saving sessions from different machines in sparse order?

**Comment by bruno-** [comment] 2015-07-29 19:40
Thank you!

> Might this be related to me saving sessions from different machines in sparse order?

Hm, I don't understand the above.. are you maybe doing a save on one machine and then trying to restore on another machine? This "feature" is not really supported. It is assumed you make a save and restore on the \*same* computer.

**Comment by foice** [comment] 2015-07-30 07:14
That is what I have done a zillion times, and worked. Now I am back to a one machine case, and it does not work anymore. Maybe makes sense to just clean the whole folder "resurrect" and start from an empty one?

**Comment by foice** [comment] 2015-07-30 13:27
cleaning up the resurrect folder did the job :)

**Comment by bruno-** [comment] 2015-08-15 20:00
Good to hear the issue is solved.
I'm going to close this one (even though we're not sure what happened there). Please report if an error happens again.

**Closed by bruno-** 2015-08-15 20:00 UTC

**Comment by foice** [comment] 2015-08-16 14:14
Actually I wanted to ask why can't I keep two branches of history of my tmux(es).

I mean if I take the bother to manually rename my `resurrect` folder on each machine I can keep saving on folder `resurrect2` on machine2 and  `resurrect1` on machine1.

What is the difficulty to script this down?

**Comment by bruno-** [comment] 2015-08-17 00:24
If I understand it correctly, you wanna be able to change the default directory where `tmux-resurrect` saves files? There's an option for this, it's [explained here](https://github.com/tmux-plugins/tmux-resurrect/blob/master/docs/save_dir.md)

**Comment by foice** [comment] 2015-08-17 07:14
Thanks a lot for suggesting this solution, I think is the right way to attack the problem.

I suppose this can be safely be a variable that depends on the hostname, e.g.

    set -g @resurrect-dir "$HOME"'/.tmux/my-resurrect/'"$HOSTNAME"'/' 

Do you see any issue with this? I am testing it and seems to work so far.

As a side thought I would ask if on pressing the "resurrect" key stroke one could get a prompt for which of the subfolders of ~/.tmux/resurrect/ to restore from, possibly with a default coming from `set -g @resurrect-dir`

**Comment by bruno-** [comment] 2015-08-17 12:06
Hey,
I tested this:

    set -g @resurrect-dir $HOME/.tmux/$HOSTNAME

and `$HOSTNAME` isn't expanded (but `$HOME` is). I'm guessing this is because `$HOSTNAME` variable isn't present in the output of `tmux show-env -g`.
If you first do `tmux set-env -g HOSTNAME foobar` then things work and resurrect will save to: `~/.tmux/foobar`.

So I think you're having this issue because tmux's environment doesn't know about `$HOSTNAME`.

Btw. after you set `@resurrect-dir`, you can check its value with `tmux show -g @resurrect-dir` command.

`~/.tmux/resurrect` is the default, but I don't think it's special by any means. Try using literal value for the directory name, eg `set -g @resurrect-dir ~/foo/bar` and things should work.

**Comment by foice** [comment] 2015-08-17 13:09
Hi, I have maybe phrased my message in a incorrect way, but $HOSTNAME is expanded just fine in my environment. However what you say could save some other person having such issues. Plus the `tmux show -g @resurrect-dir` tip is  helpful.
Thanks for stepping in.
Roberto

**Comment by bruno-** [comment] 2015-08-17 15:57
Ah, okay. I focused on the last part of your previous message. Glad to hear things work.
