### ISSUE TITLE
Error when restoring pane content

### ISSUE THREAD

**Issue by Limeth** [tmux-plugins/tmux-resurrect#141] opened 2016-04-17 13:22 UTC
When I restore the session, an error message appears at the top of all the panes which says a file or directory could not be found.

This is what I have in .tmux.conf:

```
set -g @resurrect-strategy-vim 'session'  # save vim sessions (may require the tpope/vim-obsession plugin)
set -g @resurrect-strategy-nvim 'session'  # save neovim sessions (may require the tpope/vim-obsession plugin)
set -g @resurrect-capture-pane-contents 'on'  # save pane contents
set -g @continuum-restore 'on'  # restore session on tmux start
set -g @continuum-save-interval '5'  # save session every 5 minutes (default is 15)
```

![Screenshot](http://storage5.static.itmages.com/i/16/0417/h_1460899144_2416053_7979c6e2d6.png)

**Comment by bruno-** [comment] 2016-04-18 03:02
This seems to be the problem related to `@resurrect-capture-pane-contents` option. When you "save" with this option turned "on" the content of all the tmux panes is saved in files in `~/.tmux/resurrect/pane_contents/`. For some reason you don't have anything in that dir.

- What do you have in `~/.tmux/resurrect/pane_contents/` directory? Any files there?
- Did you try just restoring with `@resurrect-capture-pane-contents` set to "on" without previously saving the whole environment?
- can you try setting `set -g @resurrect-capture-pane-contents 'on'` (make sure this option is sourced), then \*save* and \*restore*. What happens? Still getting that error?

**Comment by Limeth** [comment] 2016-04-18 13:29
`~/.tmux/resurrect/pane_contents/` is empty, even after I save the session by pressing `<prefix><C-s>`.
I already have `set -g @resurrect-capture-pane-contents 'on'` in `~/.tmux.conf`.

My tmux version is 2.3, built from source.

**Comment by sariattila** [comment] 2016-05-05 07:43
Hi. Same issue here
![selection_002](https://cloud.githubusercontent.com/assets/5034149/15038645/c4e93b80-12a5-11e6-9060-46a02bf072e4.png)

**Comment by passcod** [comment] 2016-09-18 22:28
Same issue.

**Comment by passcod** [comment] 2016-09-18 22:30
The `pane_contents.tar.gz` file seems to contain the right things though.

**Comment by ylluminarious** [comment] 2017-02-27 21:53
+1, Also seeing the same as what @passcod said:

> The `pane_contents.tar.gz` file seems to contain the right things though.

However, when I uncompress `pane_contents.tar.gz`, `tmux_resurrect` seems to ignore it and just resets the `pane_contents` directory back to an empty state once I try to reload the environment. Please fix this issue since it's currently making `tmux_resurrect` unusable for me since all I really want is for my pane(s) to have their contents restored once I restart `tmux`.

**Comment by ylluminarious** [comment] 2017-02-28 18:34
@bruno- Do you have any thoughts as to whether this issue is solvable, given that it seems that all that needs to be done here is to correctly utilize the `pane_contents.tar.gz ` file?

**Comment by tolgraven** [comment] 2017-04-19 19:09
I tried to figure out how exactly it manages to get to `pane_content_files_cleanup` before actually restoring, really doesn't make sense.
But meh, I just commented out both calls and called it a day, works fine now.

**Comment by ylluminarious** [comment] 2017-04-19 19:12
@tolgraven Could you link to which lines you specifically commented out?

**Comment by tolgraven** [comment] 2017-04-19 22:54
Sure.

```
diff --git a/scripts/restore.sh b/scripts/restore.sh
index 50d4cbb..11f852a 100755
--- a/scripts/restore.sh
+++ b/scripts/restore.sh
@@ -258,9 +258,9 @@ restore_all_panes() {
                        restore_pane "$line"
                fi
        done < $(last_resurrect_file)
-       if is_restoring_pane_contents; then
-               pane_content_files_cleanup
-       fi
+       # if is_restoring_pane_contents; then
+               # pane_content_files_cleanup
+       # fi
 }

 restore_pane_layout_for_each_window() {
diff --git a/scripts/save.sh b/scripts/save.sh
index 137e229..9edc425 100755
--- a/scripts/save.sh
+++ b/scripts/save.sh
@@ -264,7 +264,7 @@ save_all() {
                mkdir -p "$(pane_contents_dir)"
                dump_pane_contents
                pane_contents_create_archive
-               pane_content_files_cleanup
+               # pane_content_files_cleanup
        fi
        if save_bash_history_option_on; then
                dump_bash_history
```

**Comment by ylluminarious** [comment] 2017-04-19 22:56
@tolgraven Thanks! If this is a usable workaround, I guess that's all we have for now due to the prolonged inactivity on this issue.

**Comment by tolgraven** [comment] 2017-04-19 23:38
Yeah I mean I wouldn't even call it a workaround, doesn't hurt any functionality and just brings pane_contents down to the same level as the rest of the plug, not cleaning up old unused files. Non-issue in both cases, but even more so here since any dangling files will just get overwritten anyways once you recreate a pane with the same index.

**Comment by bruno-** [comment] 2017-05-30 03:55
Guys, sorry for waiting so long. I've merged #193. As I never had this issue can someone confirm this is now resolved?

**Comment by bruno-** [comment] 2017-05-30 03:59
So it just occurred to me what might be the **real** problem here: I noticed the first post in the thread has `tmux-continuum` installed with a 5 minutes interval.
That means there's a process that does `pane_content_files_cleanup` and uses the same directory as the restore process. So I think it's the tmux-continuum automated save that messed things up here..

**Comment by ylluminarious** [comment] 2017-05-30 04:18
@bruno- Wow, thanks a lot. Just updated my tmux plugins and it seems to be working now, even with `tmux-continuum` on. Thanks again for fixing this; I think we can all appreciate what a nice feature this is to finally have working.

Also, you might be right about `tmux-continuum`; I haven't tested (to my recollection) whether this issue has any correlation with it so it's quite possible that `tmux-continuum` causes the problem. However, as I said previously, it seems to be working now even with `tmux-continuum` on, so I guess it doesn't matter now.

**Comment by bruno-** [comment] 2017-05-30 04:48
Thanks for the fast feedback. So the proper solution for this is simple: just save and restore pane contents in separate directories. The fix is easy and I've implemented it locally. Will push tomorrow and ask you guys to try it out.

**Comment by ylluminarious** [comment] 2017-05-30 04:49
@bruno- Ok, thanks a lot for the info and for taking the time to fix this.

**Comment by ylluminarious** [comment] 2017-06-19 03:11
@bruno- Hey, fyi, I updated my tmux plugins recently to try out your changes and it looks like the same issue is happening again as previously discussed... i.e., there's error messages upon trying to restore pane contents such as `cat: /Users/me/.tmux/resurrect/restore/pane_contents//pane-0:0.0: No such file or directory`. I'm going to locally revert back to a working commit for the time being, but I wanted to let you know about that. Thanks.

**Comment by ylluminarious** [comment] 2017-07-04 02:55
@bruno- Fyi again, I reverted to commit `7a8d90a27d2005792415b7a6c30ae2afd6d5838d `. I just realized that I forgot to specify which commit I reverted to, after which things are broken again as before. Thanks.

**Comment by bruno-** [comment] 2017-07-08 23:20
Hey, so the patch mentioned above was pushed a day or two after May 30.. The problem you mention here https://github.com/tmux-plugins/tmux-resurrect/issues/141#issuecomment-309328508 should be fixed with b7a4ee2a40765ba23a25544211024c35e5025620.

I didn't understand your latest comment.. are things working for you now, or not?

**Comment by ylluminarious** [comment] 2017-07-09 15:15
@bruno- Sorry, you're right about my last comment being unclear; I just reread it myself and it didn't make sense until I read it yet again. Let me try to clarify:

What I mean is that whenever I use a version later than `7a8d90a`, things are broken again. I.e., I'm currently stuck at `7a8d90a`, because whenever I update (it doesn't matter if I update to `master`, `b7a4ee2`, or anything else), I get the same old error when I try to restore my panes:
```
cat: /Users/me/.tmux/resurrect/restore/pane_contents//pane-0:0.0: No such file or directory
```

**Comment by ariesdevil** [comment] 2018-01-16 10:40
same error:
cat: /Users/ariesdevil/.tmux/resurrect/restore/pane_contents//pane-2:2.1: No such file or directory

**Comment by ylluminarious** [comment] 2018-01-16 17:01
@bruno- What exactly happened after `7a8d90a` that caused this bug to regress? Everything was fine until after that commit...

**Comment by Starefossen** [comment] 2018-02-19 19:57
Same error here:

```
cat: /Users/{username}/.tmux/resurrect/restore/pane_contents//pane-main:0.0: No such file or directory
```

**Comment by ylluminarious** [comment] 2018-02-19 20:07
@Starefossen @ariesdevil Since the developer, @bruno-, is not responding to this bug anymore, the only solution I've found is to just stay on `7a8d90a`. You can do that via:

```sh
$ cd ~/.tmux/plugins/tmux-resurrect && git checkout 7a8d90a27d2005792415b7a6c30ae2afd6d5838d
```
I am really perplexed as to why this bug hasn't been fixed yet. There is a clear point of regression and there has been more than ample time to determine the issue. This bug has been open for about a year and a half now, so I am really confused as to the radio silence that this issue has received.

**Comment by Starefossen** [comment] 2018-02-19 20:18
Thanks for the quick answer @ylluminarious! Reverting to `7a8d90a` did the trick. Since it has been reverted in a later commit I guess it might have created some sort of problem with other users?

**Comment by ylluminarious** [comment] 2018-02-19 20:19
@Starefossen 

> it might have created some sort of problem with other users?

Possibly so. Still, if that is indeed the reason, we should been told so. We're just sitting in the dark on this issue right now.

**Comment by BarbzYHOOL** [comment] 2018-07-18 23:11
I did the checkout and still same problem, no file ever saved in restore dir

**Comment by ylluminarious** [comment] 2018-07-19 00:40
@BarbzYHOOL Sorry, I'm not sure what's causing your issue. That directory structure looks totally different to what I have. For me, the pane contents are stored under:

```
/Users/gdplymale/.tmux/resurrect/pane_contents
```

I see no `save` or `restore` directories.

**Comment by ylluminarious** [comment] 2018-07-19 00:40
@BarbzYHOOL Sorry, I'm not sure what's causing your issue. That directory structure looks totally different to what I have. For me, the pane contents are stored under:

```
/Users/my_username/.tmux/resurrect/pane_contents
```

I see no `save` or `restore` directories.

**Comment by BarbzYHOOL** [comment] 2018-07-19 15:15
ahh well I use byobu, not tmux, but I think it worked in the past, but I might try the fix above though

**Comment by tanc** [comment] 2018-10-30 07:58
Adding my voice to this, pane contents don't restore and I see a similar message to others:
```
cat: '/home/tanc/.tmux/resurrect/restore/pane_contents//pane-iucnflr:0.2': No such file or directory
```
`~/.tmux/resurrect` contains pane_contents.tar.gz but `~/.tmux/resurrect/restore/pane_contents` is empty as is `~/.tmux/resurrect/save/pane_contents` even after a manual save.

I have `tmux-continuum` set to save every 10 mins:
```
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-sidebar'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g status-right 'Continuum status: #{continuum_status}'
set -g @continuum-restore 'on'
set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-save-interval '10'
```

**Comment by BarbzYHOOL** [comment] 2018-11-15 16:59
I verified on an old install, I have tmux resurrect on this commit b8cc90a7f4db209d6c25d4156f8f236eec3b1dca

and it works fine (without any "restore" or "save" dir)

So I guess I'm gonna revert to this commit

**Comment by sethen** [comment] 2020-04-20 20:53
I installed this today and having the same issue as pointed out in this thread.

**Comment by ylluminarious** [comment] 2020-04-21 03:32
@sethen I've been using this plugin for years now with just my aforementioned workaround. Unfortunately I don't think it will ever get fixed at this point. But it's fine for me. My usage of this plugin is quite limited; this is basically the only thing I use it for. And I don't use it that often.

**Comment by lllbenderlll** [comment] 2020-08-18 22:33
I also have this issue on **raspberry pi 3 B**.
Before the restoration of my saved session, I do the extraction of  **~/.tmux/resurrect/pane_contents.tar.gz** to a **~/.tmux/resurrect/restore/pane_contents** folder and this ritual help. Not convenient but help.
And if you get something like this **pane-0:1.0': No such file or directory** just cat it after extraction **pane_contents.tar.gz** ...
with best regards.

**Comment by cartoonist** [comment] 2021-12-19 11:40
For some reasons (which are unknown to me), postponing *restore/pane_contents* clean-up after calling `restore_active_pane_for_each_window` ([scripts/restore.sh:392](https://github.com/tmux-plugins/tmux-resurrect/blob/6be2f34b5f06c8a6a23dc3dc835e69c132d58a18/scripts/restore.sh#L392)) fixed the issue for me. That is:

```diff
diff --git a/scripts/restore.sh b/scripts/restore.sh
index 47907bc..835e42c 100755
--- a/scripts/restore.sh
+++ b/scripts/restore.sh
@@ -270,9 +270,6 @@ restore_all_panes() {
                        restore_pane "$line"
                fi
        done < $(last_resurrect_file)
-       if is_restoring_pane_contents; then
-               rm "$(pane_contents_dir "restore")"/*
-       fi
 }

 handle_session_0() {
@@ -375,6 +372,12 @@ restore_active_and_alternate_sessions() {
        done < $(last_resurrect_file)
 }

+cleanup_restored_pane_contents() {
+       if is_restoring_pane_contents; then
+               rm "$(pane_contents_dir "restore")"/*
+       fi
+}
+
 main() {
        if supported_tmux_version_ok && check_saved_session_exists; then
                start_spinner "Restoring..." "Tmux restore complete!"
@@ -394,6 +397,7 @@ main() {
                restore_grouped_sessions  # also restores active and alt windows for grouped sessions
                restore_active_and_alternate_windows
                restore_active_and_alternate_sessions
+               cleanup_restored_pane_contents
                execute_hook "post-restore-all"
                stop_spinner
                display_message "Tmux restore complete!"

```

I have to mention that the plugin used to work perfectly when I was using bash, but it fails to restore pane contents using fish as the default shell. This patch fixed this issue for both bash and fish for me.

**Closed** 2021-12-19 15:19 UTC
Labels: bug, needs investigation

**Comment by passcod** [comment] 2021-12-19 20:29
Thanks so much for tracking this down!!1
