### ISSUE TITLE
cat: /Users/.tmux/resurrect/pane_contents//pane-jcs:5.1: No such file or directory

### ISSUE THREAD

**Issue by eternalfool** [tmux-plugins/tmux-resurrect#192] opened 2017-05-06 05:34 UTC
I get

`cat: /Users/shashwat/.tmux/resurrect/pane_contents//pane-jcs:5.1: No such file or directory`

in every window of the when I resurrect. Also none of the contents of the pane are resurrected.

**Comment by bruno-** [comment] 2017-05-30 00:09
Hm.. this feature should work nicely. It's been out for years now and worked for me personally without problems.

Would you mind providing your `tmux.conf`?

Did you try the usual stuff: completely restarting tmux after installing the plugin and/or changing some tmux-ressurect options?

**Comment by kentmartin73** [comment] 2018-03-28 14:47
Hi,

Weird, I get this too:

> cat: '/home/xxxx/.tmux/resurrect/restore/pane_contents//pane-0:0.3': No such file or directory

tmux.conf is as follows:

```
run-shell "source /usr/local/lib/python3.5/dist-packages/powerline/bindings/zsh/powerline.zsh"
# run-shell "powerline-daemon -q"

# source /usr/local/lib/python3.5/dist-packages/powerline/bindings/tmux/powerline_tmux_2.1_plus.conf
source /usr/local/lib/python3.5/dist-packages/powerline/bindings/tmux/powerline.conf

set -g mouse on
# to enable mouse scroll, see https://github.com/tmux/tmux/issues/145#issuecomment-150736967
# run-shell ~/.tmux-better-mouse-mode/scroll_copy_mode.tmux
set -ga terminal-overrides ',:xterm*:smcup@:rmcup@'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
# Needed to make copy clipboard work on OSX (on some versions)
# set-option -g default-command "reattach-to-user-namespace -l zsh"

set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'

# History searching controlled with / then n & N
set -g @plugin 'tmux-plugins/tmux-copycat'

# Save and resurrect sessions
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '1'
set -g @resurrect-capture-pane-contents 'on'

# Clipboard handling
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xclip -i -f -selection primary | xclip -i -selection clipboard"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

```
I'm using zsh, if there's anything else relevant, I'm happy to provide it.

Cheers,

Kent

**Comment by arooni** [comment] 2018-05-09 01:52
i also have this issue

cat: '/home/david/.tmux/resurrect/restore/pane_contents//pane-SysAdmin:0.0': No such file or directory

**Comment by jzacsh** [comment] 2018-07-31 16:53
same as @kentmartin73  - only in a single pane, but other panes restore well. it seems this is a duplicate of #141

**Comment by orcinus** [comment] 2019-02-22 22:14
Same issue here. On 6 out of 9 panes (across two workspaces).

**Comment by wizonesolutions** [comment] 2019-08-10 12:39
Do any of you use fish? I ran into this when I had the `default-shell` set to `fish`. I'm working around it the same way I do in my terminal programs: keeping Bash and just starting up fish immediately. Works great:

```
# Just let bash set the environment, then drop to fish.
set-option -g default-command /usr/bin/fish
```

**Comment by orcinus** [comment] 2019-08-10 14:20
> Do any of you use fish?

Yes!

> I'm working around it the same way I do in my terminal programs: keeping Bash and just starting up fish immediately. Works great

But will that restore the pane states?

**Comment by wizonesolutions** [comment] 2019-08-10 15:26
@orcinus It has restored the pane states at least once for me (I `pkill`'ed tmux and then `tmux new -d`'d, and history came back). tmux crashed another time because I think my save interval was too frequent with tmux-continuum, and I don't think the history came back that time.

I'll keep an eye on this and try to remember to post back here if I have to do more. But I'm at least not getting fish startup/PATH issues now, Linuxbrew works fine, etc.

**Closed** 2021-12-19 15:19 UTC
