### ISSUE TITLE
Restoring multiple sessions 

### ISSUE THREAD

**Issue by philiprhoades** [tmux-plugins/tmux-resurrect#182] opened 2017-02-23 13:53 UTC
People,
I just installed tmux-resurrect and it looks nice but it doesn't seem to restore multiple sessions?  I use XFCE4 with four workspaces and a tmux session in each but using "CTRL-b CTRL-r" is only able to restore one session (and actually the wrong session for the workspace I was in) - am I missing something?
Thanks,
Phil.

**Comment by philiprhoades** [comment] 2017-02-23 14:44
I have found a way of doing what I want but it is a little slow:
- start tmux in any workspace
- use "CTRL-b CTRL-r"
- use "CTRL-b s"
to list the restored sessions and change to the appropriate session for the current workspace
- repeat "tmux" ; "CTRL-b s"
for other workspaces and choose appropriate session for each . .
It would be VERY nice if doing "CTRL-b CTRL-r" could restore ALL sessions to their appropriate workspaces in one hit . . 
P.

**Comment by falzard** [comment] 2017-03-25 17:21
Hmm, I feel like you misunderstood the program like me and like many people at first sight.

I suppose you tested to restore only ONE session at a time. Try to create two different new sessions, save one session, and delete these two sessions.
Now open a new session and load your saved session. What happens? All the sessions are loaded, the 2 sessions you deleted are now loaded and the sessions that you didn't kill are not modified, they are left untouched (hence why it is confusing).

**Comment by bruno-** [comment] 2017-05-29 22:03
@philiprhoades tmux and tmux-resurrect are unaware of the external XFCE4 environment and its workspaces.

As you said in the second post above: yes, all the sessions are restored. **The focus will be on the session where you last performed resurrect save via "ctrl-b ctrl-s"**

**Comment by bruno-** [comment] 2017-06-01 04:02
Hey peeps, gonna close this one as it seems everything behaves as intended here. Pls reopen if you have more to add.

**Closed by bruno-** 2017-06-01 04:02 UTC
Labels: waiting for reply
