### ISSUE TITLE
restore pane names but not path

### ISSUE THREAD

**Issue by foice** [tmux-plugins/tmux-resurrect#80] opened 2015-03-29 10:11 UTC
Hello I have just installed (after compiling as non-root user) tmux 1.9a and have now resurrect running on my machine.

I have opened a few panes and moved to different folders,just to check if save&resurrect was working... I am afraid there is some problem.

I tested it like this.

tmux
prefix + c
cd some folder
prefix + c
cd some folder
prefix + CTRL+s (to save)
prefix + d  (to detach)
tmux kill-session -t 0 (to "simulate" my sysadmin turning off this machine without telling me)
tmux
prefix + CTRL + r 

At this point I was expecting all to be restored, panes and path of each pane, but only the panes and their names were restored, the paths where not ... 

Here is my "last"

```
pane    0       1       :LSF Monitor    0       :       0       :/gpfs/ddn/users/rfrances       1       bash    :
pane    0       2       :mcfm_mtop_mu_scan.sh   0       :       0       :/gpfs/ddn/users/rfrances       1       bash    :
pane    0       3       :tt_todk_multiR_production      1       :*      0       :/gpfs/ddn/users/rfrances/MCFM-6.8/tt_todk_multiR_production    1       bash    :
pane    0       4       :resurrect      0       :-      0       :/gpfs/ddn/users/rfrances/.tmux/resurrect       1       bash    :
window  0       1       0       :       b07e,142x41,0,0,1
window  0       2       0       :       b07f,142x41,0,0,2
window  0       3       1       :*      b080,142x41,0,0,3
window  0       4       0       :-      b081,142x41,0,0,4
```

and my tmux.conf

```
set -g prefix C-a
unbind C-b
bind-key a send-prefix
bind-key C-a last-window
unbind-key '"'
bind-key '"' choose-window
set -g base-index 1
#set -g @continuum-save-interval '60'

# List of plugins
# Supports `github_username/repo` or full git repo URLs
set -g @tpm_plugins '              \
  tmux-plugins/tpm                 \
  tmux-plugins/tmux-resurrect      \
  tmux-plugins/tmux-continuum      \
  tmux-plugins/tmux-sensible       \
'
# Other examples:
# github_username/plugin_name    \
# git@github.com/user/plugin     \
# git@bitbucket.com/user/plugin  \

# Initializes TMUX plugin manager.
# Keep this line at the very bottom o
```

Thanks for helping,
Roberto

PS
I do not see a way to attach file in this interfase (it's my first issue!) so, excuse me if the cut-paste of the files were painful to read.

**Comment by bruno-** [comment] 2015-03-30 12:15
Hey, congratulations on your first github issue!
Opening issues and providing quality, detailed info (as in your case above) is always helpful, so thanks for that.

> I do not see a way to attach file in this interfase (it's my first issue!) so, excuse me if the cut-paste of the files were painful to read.

I just fixed this in you issue. The trick is to surround file or code contents with triple backtick characters. This is explained in the [help here](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks).

About the issue with `tmux-resurrect`, not sure what is causing this.. The paths in the "last" file, for example this one `/gpfs/ddn/users/rfrances/MCFM-6.8/tt_todk_multiR_production` this looks good, right?

Also when you type `cd /gpfs/ddn/users/rfrances/MCFM-6.8/tt_todk_multiR_production` in the shell, the directory changes ok?

This reminds me of bug #50, which turned out to be bug in tmux core. To test, when inside tmux, can you please try executing the following commands:

- `tmux split-window -c "/gpfs/ddn/users/rfrances/MCFM-6.8/tt_todk_multiR_production"`
- `tmux new-window -c "/gpfs/ddn/users/rfrances/MCFM-6.8/tt_todk_multiR_production"`

For the above commands a new window split or a new window should open \*inside\* the directory specified with the `-c` flag.
Can you please let me know the result?

**Comment by foice** [comment] 2015-03-30 12:23
Thanks a lot for taking the time to give a look at this issue.

```cd /gpfs/ddn/users/rfrances/MCFM-6.8/tt_todk_multiR_production` works fine from bash and inside tmux as well.```

I tried these commands from bash and from inside tmux. The result of the new-windows is to make a new window in the home folder, instead of the specified path. The split-window does the same, a new pane in my home instead of the specified folder.

I hope this helps.

**Comment by bruno-** [comment] 2015-03-30 12:36
Hey!

> I tried these commands from bash and from inside tmux. The result of the new-windows is to make a new window in the home folder, instead of the specified path. The split-window does the same, a new pane in my home instead of the specified folder.

> I hope this helps.

This sure helps.. unfortunately if split windows are opening in home dir, it seems the tmux `-c` flag is broken. There's nothing we can do about it from the context of this plugin.

As mentioned previously, this was already reported in issue #50. Subsequently the issue to tmux core was opened here: http://sourceforge.net/p/tmux/tickets/155/

One last check: are you using `zsh`? Apparently, a user experienced this same problem, but that was caused by `zsh` plugin. Can you check [here](https://github.com/tmux-plugins/tmux-resurrect/issues/50#issuecomment-70463838) for his 2 comments.

If that does not help would you mind leaving comment in http://sourceforge.net/p/tmux/tickets/155/
with details about your operating system, environment etc.

**Comment by foice** [comment] 2015-03-30 13:51
Hello, I am using ```bash```  as per my 
```~>echo $SHELL
/bin/bash``` so the zsh plugin thing should not be applicable here, I suppose.

I am leaving a mark on the tmux core bug tracker as well. Would be nice if this can be fixed.

Thanks for your help.

**Comment by bruno-** [comment] 2015-04-02 12:39
I'm glad we clarified this, but sorry I couldn't do much..
I'll close this issue since it's pretty much a duplicate of #50.

**Closed by bruno-** 2015-04-02 12:39 UTC
